all:	icache_test dcache_test
icache_test:	icache_test.c
	gcc -O0 icache_test.c -o icache_test	
dcache_test:	dcache_test.c
	gcc -O0 dcache_test.c -o dcache_test	
clean:	
	rm -rf icache_test dcache_test
